FROM mhart/alpine-node:12

# install dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --production

###
# Only copy over the Node pieces we need
# ~> Saves 35MB
###
FROM mhart/alpine-node:slim-12

WORKDIR /app
COPY --from=0 /app .
COPY . .

# Set environment variables and port
ENV NODE_ENV production
ENV PORT 3000
EXPOSE 3000

ENTRYPOINT ["node", "__sapper__/build"]
